
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataAttribute : Luban.BeanBase
{
    public DataAttribute(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["comment"].IsString) { throw new SerializationException(); }  Comment = _buf["comment"]; }
        { if(!_buf["HP_MAX"].IsNumber) { throw new SerializationException(); }  HPMAX = _buf["HP_MAX"]; }
        { if(!_buf["MP_MAX"].IsNumber) { throw new SerializationException(); }  MPMAX = _buf["MP_MAX"]; }
        { if(!_buf["ATK"].IsNumber) { throw new SerializationException(); }  ATK = _buf["ATK"]; }
        { if(!_buf["DEF"].IsNumber) { throw new SerializationException(); }  DEF = _buf["DEF"]; }
        { if(!_buf["ATK_RAN"].IsNumber) { throw new SerializationException(); }  ATKRAN = _buf["ATK_RAN"]; }
        { if(!_buf["SPEED"].IsNumber) { throw new SerializationException(); }  SPEED = _buf["SPEED"]; }
        { if(!_buf["Size"].IsNumber) { throw new SerializationException(); }  Size = _buf["Size"]; }
        { if(!_buf["CRITICAL_RATE"].IsNumber) { throw new SerializationException(); }  CRITICALRATE = _buf["CRITICAL_RATE"]; }
        { if(!_buf["CRITICAL_DAMAGE_RATE"].IsNumber) { throw new SerializationException(); }  CRITICALDAMAGERATE = _buf["CRITICAL_DAMAGE_RATE"]; }
        { if(!_buf["BASE_HP_RECOVERY"].IsNumber) { throw new SerializationException(); }  BASEHPRECOVERY = _buf["BASE_HP_RECOVERY"]; }
        { if(!_buf["BASE_MP_RECOVERY"].IsNumber) { throw new SerializationException(); }  BASEMPRECOVERY = _buf["BASE_MP_RECOVERY"]; }
        { if(!_buf["HP_RECOVERY"].IsNumber) { throw new SerializationException(); }  HPRECOVERY = _buf["HP_RECOVERY"]; }
        { if(!_buf["MP_RECOVERY"].IsNumber) { throw new SerializationException(); }  MPRECOVERY = _buf["MP_RECOVERY"]; }
        { if(!_buf["ATTACK_SPEED"].IsNumber) { throw new SerializationException(); }  ATTACKSPEED = _buf["ATTACK_SPEED"]; }
        { if(!_buf["SLOWING"].IsNumber) { throw new SerializationException(); }  SLOWING = _buf["SLOWING"]; }
        { if(!_buf["BREAK_SHIELD_PER"].IsNumber) { throw new SerializationException(); }  BREAKSHIELDPER = _buf["BREAK_SHIELD_PER"]; }
        { if(!_buf["BREAK_SHIELD_NUM"].IsNumber) { throw new SerializationException(); }  BREAKSHIELDNUM = _buf["BREAK_SHIELD_NUM"]; }
        { if(!_buf["INIT_LV"].IsNumber) { throw new SerializationException(); }  INITLV = _buf["INIT_LV"]; }
        { if(!_buf["ATTACK_SPEED_POWER"].IsNumber) { throw new SerializationException(); }  ATTACKSPEEDPOWER = _buf["ATTACK_SPEED_POWER"]; }
        { if(!_buf["BASE_ATTACK_SPEED"].IsNumber) { throw new SerializationException(); }  BASEATTACKSPEED = _buf["BASE_ATTACK_SPEED"]; }
    }

    public static DataAttribute DeserializeDataAttribute(JSONNode _buf)
    {
        return new DataAttribute(_buf);
    }

    /// <summary>
    /// 属性包ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 策划备注
    /// </summary>
    public readonly string Comment;
    /// <summary>
    /// 生命值上限
    /// </summary>
    public readonly int HPMAX;
    /// <summary>
    /// 魔法值上限
    /// </summary>
    public readonly int MPMAX;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int ATK;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int DEF;
    /// <summary>
    /// 攻击范围
    /// </summary>
    public readonly int ATKRAN;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int SPEED;
    /// <summary>
    /// 体型大小
    /// </summary>
    public readonly int Size;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CRITICALRATE;
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public readonly float CRITICALDAMAGERATE;
    /// <summary>
    /// 基础生命恢复
    /// </summary>
    public readonly int BASEHPRECOVERY;
    /// <summary>
    /// 基础魔法恢复
    /// </summary>
    public readonly int BASEMPRECOVERY;
    /// <summary>
    /// 生命回复效果
    /// </summary>
    public readonly float HPRECOVERY;
    /// <summary>
    /// 魔法回复效果
    /// </summary>
    public readonly float MPRECOVERY;
    /// <summary>
    /// 攻击速度
    /// </summary>
    public readonly float ATTACKSPEED;
    /// <summary>
    /// 减速效果
    /// </summary>
    public readonly float SLOWING;
    /// <summary>
    /// 百分比破防
    /// </summary>
    public readonly float BREAKSHIELDPER;
    /// <summary>
    /// 固定破防
    /// </summary>
    public readonly int BREAKSHIELDNUM;
    /// <summary>
    /// 初始等级
    /// </summary>
    public readonly int INITLV;
    /// <summary>
    /// 攻速权重
    /// </summary>
    public readonly float ATTACKSPEEDPOWER;
    /// <summary>
    /// 基础攻速
    /// </summary>
    public readonly float BASEATTACKSPEED;
   
    public const int __ID__ = -993261070;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "comment:" + Comment + ","
        + "HPMAX:" + HPMAX + ","
        + "MPMAX:" + MPMAX + ","
        + "ATK:" + ATK + ","
        + "DEF:" + DEF + ","
        + "ATKRAN:" + ATKRAN + ","
        + "SPEED:" + SPEED + ","
        + "Size:" + Size + ","
        + "CRITICALRATE:" + CRITICALRATE + ","
        + "CRITICALDAMAGERATE:" + CRITICALDAMAGERATE + ","
        + "BASEHPRECOVERY:" + BASEHPRECOVERY + ","
        + "BASEMPRECOVERY:" + BASEMPRECOVERY + ","
        + "HPRECOVERY:" + HPRECOVERY + ","
        + "MPRECOVERY:" + MPRECOVERY + ","
        + "ATTACKSPEED:" + ATTACKSPEED + ","
        + "SLOWING:" + SLOWING + ","
        + "BREAKSHIELDPER:" + BREAKSHIELDPER + ","
        + "BREAKSHIELDNUM:" + BREAKSHIELDNUM + ","
        + "INITLV:" + INITLV + ","
        + "ATTACKSPEEDPOWER:" + ATTACKSPEEDPOWER + ","
        + "BASEATTACKSPEED:" + BASEATTACKSPEED + ","
        + "}";
    }
}

}
