
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataLevel : Luban.BeanBase
{
    public DataLevel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["round_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } RoundIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RoundIds.Add(__v0); }   }
        { var __json0 = _buf["init_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } InitIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InitIds.Add(__v0); }   }
    }

    public static DataLevel DeserializeDataLevel(JSONNode _buf)
    {
        return new DataLevel(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 回合id数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> RoundIds;
    /// <summary>
    /// 初始配置id数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitIds;
   
    public const int __ID__ = 1622611418;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "roundIds:" + Luban.StringUtil.CollectionToString(RoundIds) + ","
        + "initIds:" + Luban.StringUtil.CollectionToString(InitIds) + ","
        + "}";
    }
}

}
