
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level_temple
{
public partial class TbWaves
{
    private readonly System.Collections.Generic.Dictionary<int, DataWave> _dataMap;
    private readonly System.Collections.Generic.List<DataWave> _dataList;
    
    public TbWaves(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataWave>();
        _dataList = new System.Collections.Generic.List<DataWave>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataWave _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataWave.DeserializeDataWave(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataWave> DataMap => _dataMap;
    public System.Collections.Generic.List<DataWave> DataList => _dataList;

    public DataWave GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataWave Get(int key) => _dataMap[key];
    public DataWave this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

