
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level_temple
{
public partial class TbLevels
{
    private readonly System.Collections.Generic.Dictionary<int, DataLevel> _dataMap;
    private readonly System.Collections.Generic.List<DataLevel> _dataList;
    
    public TbLevels(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataLevel>();
        _dataList = new System.Collections.Generic.List<DataLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataLevel.DeserializeDataLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<DataLevel> DataList => _dataList;

    public DataLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataLevel Get(int key) => _dataMap[key];
    public DataLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

