
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level_temple
{
public partial class TbInitConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DataInitConfig> _dataMap;
    private readonly System.Collections.Generic.List<DataInitConfig> _dataList;
    
    public TbInitConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataInitConfig>();
        _dataList = new System.Collections.Generic.List<DataInitConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataInitConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataInitConfig.DeserializeDataInitConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataInitConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DataInitConfig> DataList => _dataList;

    public DataInitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataInitConfig Get(int key) => _dataMap[key];
    public DataInitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

