
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.piece
{
public partial class TbPieceDefender
{
    private readonly System.Collections.Generic.Dictionary<int, DataDefender> _dataMap;
    private readonly System.Collections.Generic.List<DataDefender> _dataList;
    
    public TbPieceDefender(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataDefender>();
        _dataList = new System.Collections.Generic.List<DataDefender>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataDefender _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataDefender.DeserializeDataDefender(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataDefender> DataMap => _dataMap;
    public System.Collections.Generic.List<DataDefender> DataList => _dataList;

    public DataDefender GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataDefender Get(int key) => _dataMap[key];
    public DataDefender this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

