
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.piece
{
public partial class TbPieceAttacker
{
    private readonly System.Collections.Generic.Dictionary<int, DataAttacker> _dataMap;
    private readonly System.Collections.Generic.List<DataAttacker> _dataList;
    
    public TbPieceAttacker(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataAttacker>();
        _dataList = new System.Collections.Generic.List<DataAttacker>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataAttacker _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataAttacker.DeserializeDataAttacker(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataAttacker> DataMap => _dataMap;
    public System.Collections.Generic.List<DataAttacker> DataList => _dataList;

    public DataAttacker GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataAttacker Get(int key) => _dataMap[key];
    public DataAttacker this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

