
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.piece
{ 
    [System.Flags]
    public enum emPieceType
    {
        DefenderPawn = 1,
        DefenderElite = 2,
        DefenderBoss = 4,
        AttackerPawn = 8,
        AttackerElite = 16,
        AttackerBoss = 32,
    }

} 

