
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public piece.TbPieceDefender TbPieceDefender {get; }
    public piece.TbPieceDefenderTemp TbPieceDefenderTemp {get; }
    public piece.TbPieceAttacker TbPieceAttacker {get; }
    public piece.TbPieceAttackerTemp TbPieceAttackerTemp {get; }
    public piece.TbPieceAttribute TbPieceAttribute {get; }
    public level_temple.TbLevels TbLevels {get; }
    public level_temple.TbWaves TbWaves {get; }
    public level_temple.TbRounds TbRounds {get; }
    public level_temple.TbInitConfig TbInitConfig {get; }
    public level_temple.TbDeployConfig TbDeployConfig {get; }
    public vfx.TbVFXConfig TbVFXConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbPieceDefender = new piece.TbPieceDefender(loader("piece_tbpiecedefender"));
        TbPieceDefenderTemp = new piece.TbPieceDefenderTemp(loader("piece_tbpiecedefendertemp"));
        TbPieceAttacker = new piece.TbPieceAttacker(loader("piece_tbpieceattacker"));
        TbPieceAttackerTemp = new piece.TbPieceAttackerTemp(loader("piece_tbpieceattackertemp"));
        TbPieceAttribute = new piece.TbPieceAttribute(loader("piece_tbpieceattribute"));
        TbLevels = new level_temple.TbLevels(loader("level_temple_tblevels"));
        TbWaves = new level_temple.TbWaves(loader("level_temple_tbwaves"));
        TbRounds = new level_temple.TbRounds(loader("level_temple_tbrounds"));
        TbInitConfig = new level_temple.TbInitConfig(loader("level_temple_tbinitconfig"));
        TbDeployConfig = new level_temple.TbDeployConfig(loader("level_temple_tbdeployconfig"));
        TbVFXConfig = new vfx.TbVFXConfig(loader("vfx_tbvfxconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbPieceDefender.ResolveRef(this);
        TbPieceDefenderTemp.ResolveRef(this);
        TbPieceAttacker.ResolveRef(this);
        TbPieceAttackerTemp.ResolveRef(this);
        TbPieceAttribute.ResolveRef(this);
        TbLevels.ResolveRef(this);
        TbWaves.ResolveRef(this);
        TbRounds.ResolveRef(this);
        TbInitConfig.ResolveRef(this);
        TbDeployConfig.ResolveRef(this);
        TbVFXConfig.ResolveRef(this);
    }
}

}
