
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataInitConfig : Luban.BeanBase
{
    public DataInitConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["item_id"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { var __json0 = _buf["item_pos"]; if(!__json0.IsArray) { throw new SerializationException(); } ItemPos = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ItemPos.Add(__v0); }   }
    }

    public static DataInitConfig DeserializeDataInitConfig(JSONNode _buf)
    {
        return new DataInitConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 棋盘物体id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 物体坐标
    /// </summary>
    public readonly System.Collections.Generic.List<int> ItemPos;
   
    public const int __ID__ = -1335798820;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + ItemId + ","
        + "itemPos:" + Luban.StringUtil.CollectionToString(ItemPos) + ","
        + "}";
    }
}

}
