
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataVFX : Luban.BeanBase
{
    public DataVFX(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["isLoop"].IsBoolean) { throw new SerializationException(); }  IsLoop = _buf["isLoop"]; }
        { if(!_buf["res_path"].IsString) { throw new SerializationException(); }  ResPath = _buf["res_path"]; }
    }

    public static DataVFX DeserializeDataVFX(JSONNode _buf)
    {
        return new DataVFX(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 是否循环
    /// </summary>
    public readonly bool IsLoop;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string ResPath;
   
    public const int __ID__ = -1187128418;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "description:" + Description + ","
        + "isLoop:" + IsLoop + ","
        + "resPath:" + ResPath + ","
        + "}";
    }
}

}
