
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataDeployConfig : Luban.BeanBase
{
    public DataDeployConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["item_id"]; if(!__json0.IsArray) { throw new SerializationException(); } ItemId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ItemId.Add(__v0); }   }
    }

    public static DataDeployConfig DeserializeDataDeployConfig(JSONNode _buf)
    {
        return new DataDeployConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 部署棋子的ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> ItemId;
   
    public const int __ID__ = 1770696691;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + Luban.StringUtil.CollectionToString(ItemId) + ","
        + "}";
    }
}

}
