
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DataRound : Luban.BeanBase
{
    public DataRound(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["wave_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } WaveIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  WaveIds.Add(__v0); }   }
        { if(!_buf["deploy_config_id"].IsNumber) { throw new SerializationException(); }  DeployConfigId = _buf["deploy_config_id"]; }
    }

    public static DataRound DeserializeDataRound(JSONNode _buf)
    {
        return new DataRound(_buf);
    }

    /// <summary>
    /// 回合id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 包含波次的id
    /// </summary>
    public readonly System.Collections.Generic.List<int> WaveIds;
    /// <summary>
    /// 玩家可部署棋子的配置（0为保持不变）
    /// </summary>
    public readonly int DeployConfigId;
   
    public const int __ID__ = 1628449764;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "waveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
        + "deployConfigId:" + DeployConfigId + ","
        + "}";
    }
}

}
