
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.level_temple
{
public partial class TbRounds
{
    private readonly System.Collections.Generic.Dictionary<int, DataRound> _dataMap;
    private readonly System.Collections.Generic.List<DataRound> _dataList;
    
    public TbRounds(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataRound>();
        _dataList = new System.Collections.Generic.List<DataRound>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataRound _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataRound.DeserializeDataRound(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataRound> DataMap => _dataMap;
    public System.Collections.Generic.List<DataRound> DataList => _dataList;

    public DataRound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataRound Get(int key) => _dataMap[key];
    public DataRound this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

