
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.piece
{
public partial class TbPieceDefenderTemp
{
    private readonly System.Collections.Generic.Dictionary<int, DataDefenderTemp> _dataMap;
    private readonly System.Collections.Generic.List<DataDefenderTemp> _dataList;
    
    public TbPieceDefenderTemp(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataDefenderTemp>();
        _dataList = new System.Collections.Generic.List<DataDefenderTemp>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataDefenderTemp _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataDefenderTemp.DeserializeDataDefenderTemp(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataDefenderTemp> DataMap => _dataMap;
    public System.Collections.Generic.List<DataDefenderTemp> DataList => _dataList;

    public DataDefenderTemp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataDefenderTemp Get(int key) => _dataMap[key];
    public DataDefenderTemp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

