
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.piece
{
public partial class TbPieceAttackerTemp
{
    private readonly System.Collections.Generic.Dictionary<int, DataAttackerTemp> _dataMap;
    private readonly System.Collections.Generic.List<DataAttackerTemp> _dataList;
    
    public TbPieceAttackerTemp(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataAttackerTemp>();
        _dataList = new System.Collections.Generic.List<DataAttackerTemp>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DataAttackerTemp _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DataAttackerTemp.DeserializeDataAttackerTemp(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DataAttackerTemp> DataMap => _dataMap;
    public System.Collections.Generic.List<DataAttackerTemp> DataList => _dataList;

    public DataAttackerTemp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataAttackerTemp Get(int key) => _dataMap[key];
    public DataAttackerTemp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

